---
title: "[EDA] ALPHA Camp PartI"
author: "Su-Fang Yeh"
date: "2022/7/3"
output: html_document
theme:cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 資料讀取

```{r,message=FALSE}
library(tidyverse)
library(knitr)

setwd("H:\\我的雲端硬碟\\0-學習\\資料集 Dataset\\AlphaCamp-SQL-AC 找出影響學習投入的原因")

students=read.csv("table1.students.csv",fileEncoding = 'UTF-8',stringsAsFactors = T)
for (i in 1:nrow(students)){
  if (students$班級[i] %in% c('7月班','8月班','9月班')){students$class_group[i]="class_Q3"}
  else{students$class_group[i]="class_Q4"}
  }

demographic=read.csv("table2.demographic.csv",fileEncoding = 'UTF-8',stringsAsFactors = T)
sessions=read_csv('table3.sessions.csv', locale= locale(encoding='UTF-8'))
submissions=read_csv('table4.submissions.csv', locale= locale(encoding='UTF-8'))
assignments=read_csv('table5.assignments.csv', locale= locale(encoding='UTF-8'))
```

# Q4 班級具體的落後程度為何？

## 作業完成率比較

`nrow(distinct(submissions["student_id"]))` = 2789 -> 有3人沒交作業

`filter(temp, is.na(id)==TRUE)` -> 找出沒交作業的人

```{r, message=FALSE}
temp=merge(submissions, students[c("id","class_group")], by.x="student_id",by.y="id", all.y=TRUE)
submission_cal<-temp %>% group_by(class_group,student_id) %>%
  summarise(
    #n_submission=n(),
    n_submission=length(na.omit(id)), # let those who did not submit as 0
    submission_rate=round(n_submission/15,2)
  )

class_trend<-submission_cal %>% group_by(class_group) %>%
  summarise(
    N=n(),
    Mean=round(mean(submission_rate),2),
    Median=median(submission_rate),
    Q1=quantile(submission_rate)[2],
    Q3=quantile(submission_rate)[4],
    IQR=Q3-Q1,
    Min=min(submission_rate),
    Max=max(submission_rate),
    Range=Max-Min
    )

kable(class_trend)

```
```{r, message=FALSE}
bin_w=(max(submission_cal$submission_rate)-min(submission_cal$submission_rate))/(1+log2(length(submission_cal$submission_rate)))

(p <- submission_cal %>%
  ggplot( aes(x=submission_rate)) +
    geom_histogram( binwidth=bin_w, fill="#69b3a2",color="#e9ecef") +
    geom_vline(data=class_trend, aes(xintercept = Mean),linetype="dashed", color="red")+
    geom_vline(data=class_trend, aes(xintercept = Median),linetype="longdash",color="blue")+
    geom_text(data=class_trend,aes(x=Mean+0.02, y=220), color="red",
              label=paste("Mean=",as.character(class_trend$Mean)), angle=270, size=3.98)+
    geom_text(data=class_trend,aes(x=Median+0.02, y=218), color="blue",
              label=paste("Median=",as.character(class_trend$Median)), angle=270, size=3.98)+
    facet_wrap(~class_group)) +
    theme(strip.text.x = element_text(size = 12),
          axis.text.x = element_text(size=10,vjust = -1),
          axis.text.y = element_text(size=10),
          axis.title.x = element_text(vjust = -3),
          axis.title.y = element_text(vjust = 3),
          plot.margin = unit(c(1,1,1,1), "cm")
          )+
    labs(x="作業完成率", y="人次")

```
```{r, message=FALSE}
(p <- submission_cal %>%
     ggplot(aes(x=as.factor(class_group),y=submission_rate*100)) +
     geom_boxplot(fill="#69b3a2")+
     geom_label(data=class_trend,aes(y=Median*100),
               label=class_trend$Median*100,
               size=3.98,fill="#69b3a2", alpha=0.8,label.size = NA)+
     geom_label(data=class_trend,aes(y=Min*100),
               label=class_trend$Min*100,
               size=3.98, fill="#ebebeb",alpha=0.4,label.size = NA)+
     geom_label(data=class_trend,aes(y=Max*100),
               label=class_trend$Max*100,
               size=3.98,  fill="#ebebeb",alpha=0.4,label.size = NA)+
     geom_label(data=class_trend,aes(y=Q1*100),
               label=class_trend$Q1*100,
               size=3.98, fill="#69b3a2",alpha=0.1,label.size = NA)+
     geom_label(data=class_trend,aes(y=Q3*100),
               label=class_trend$Q3*100,
               size=3.98, fill="#69b3a2",alpha=0.1,label.size = NA)+
     theme(axis.text.x = element_text(size=12,vjust = -1),
          axis.text.y = element_text(size=10),
          axis.title.x = element_text(vjust = -3),
          axis.title.y = element_text(vjust = 5),
          plot.margin = unit(c(1,1,1,1), "cm"),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()
          )+
     labs(y="作業完成率 (%)", x="班次"))
```

```{r}
concat_tb=table(submission_cal$class_group,as.factor(submission_cal$n_submission))
chisq.test(concat_tb,simulate.p.value = TRUE) 

```

## 學習時間

`nrow(distinct(sessions["student_id"]))` -> 每個人都有上線紀錄

```{r,echo=FALSE, message=FALSE}
session_time <-sessions %>% 
  group_by(student_id) %>% summarise(
    online_t=sum(`學習時間（分鐘）`)/60,
    meet_expect=(online_t>=(45)),
    freq=length(id)
  ) %>% 
  merge(students[c("id","class_group")], by.x="student_id",by.y="id")

(session_cal<-session_time%>%group_by(class_group) %>% summarise(
  N=n(),
  Mean=mean(online_t),
  Median=median(online_t),
  meet_expect_N=sum(meet_expect),
  meet_expect_portion=round(meet_expect_N/N,2),
  not_meet_expect_potion=1- meet_expect_portion,
  Mean_hour= (mean(online_t))
) )

```


```{r, message=FALSE}
session_cal %>% 
  gather("condition","portion",meet_expect_portion,not_meet_expect_potion)%>%
  arrange(desc(portion)) %>%
  ggplot(aes(fill=condition, y=portion, x=class_group))+
  geom_bar(position="fill", stat="identity")+ 
  coord_flip()

```

```{r, message=FALSE}
# 比例檢定
prop.test(session_cal$meet_expect_N,session_cal$N, alternative="two.sided") 


```


```{r, message=FALSE}
bins=session_time%>% group_by(class_group) %>% summarise(
  bin_w=(max(online_t)-min(online_t))/(1+log2(length(online_t)))
)


p1<-filter(session_time,class_group=="class_Q3") %>% 
    ggplot( aes(x=online_t)) +
    geom_histogram(binwidth=bins$bin_w[1],fill="#69b3a2",color="#e9ecef")+
    geom_vline(aes(xintercept = 45),linetype="longdash", color="#006000")+
    #geom_text(aes(x=45, y=110), color="#006000",
              #label="建議最低學習時數(45h)", size=3.6, hjust=-0.05)+
    labs(x="學習時間",y="人次", title="class_Q3")+
    theme(plot.title = element_text(hjust = 0.5))+
    xlim(0,max(session_time$online_t)+max(bins$bin_w))

p2<-filter(session_time,class_group=="class_Q4") %>% 
    ggplot( aes(x=online_t)) +
    geom_histogram(binwidth=bins$bin_w[2],fill="#69b3a2",color="#e9ecef")+
    geom_vline(aes(xintercept = 45),linetype="longdash", color="#006000")+
    #scale_color_manual(name = "statistics", values = c(建議學習時數="#006000"))+
    #geom_text(aes(x=45, y=110), color="#006000",
             # label="建議最低學習時數(45h)", size=3.6, hjust=-0.05)+
    labs(x="學習時間",y="人次",title="class_Q4")+
    theme(plot.title = element_text(hjust = 0.5))+
    xlim(0,max(session_time$online_t)+5)

library(gridExtra)
grid.arrange(p1, p2, ncol = 2)

```

## 作業繳交 vs 學習時間

```{r,echo=FALSE, message=FALSE}

ggplot(cbind(submission_cal,session_time$online_t))+
  geom_bar(aes(submission_cal$n_submission,mean(session_time$online_t)),stat = "identity")+
  facet_wrap(~class_group)

```

## 學習頻率

總共上線幾次

```{r,echo=FALSE, message=FALSE}

ggplot(session_time)+
  geom_bar(aes(session_time$freq),fill="#69b3a2")+
  facet_wrap(~class_group)+
  labs(x="上線次數",y="人次")

```
```{r}
# 卡方檢定
concat_tb=table(session_time$class_group,session_time$freq)
chisq.test(concat_tb) 
```
